Feature/main menu
radekwojpl2/CodersCamp2020.CookBook pull request #14
Opened 2021-01-01 20:30 UTC by MaDud

Create basic structure for menu with toggle btn for mobile view.

2021-01-05 19:42 UTC, kingam280 approved these changes

2021-01-13 21:38 UTC, kingam280 approved these changes

2021-01-13 21:52 UTC, radekwojpl2 commented on src/index.js
>  const QUIZ_MAX_TIME = process.env.QUIZ_MAX_TIME_SECONDS ? process.env.QUIZ_MAX_TIME_SECONDS * ONE_SECOND_MILLIS : 120 * ONE_SECOND_MILLIS;
do we need this variable ?

2021-01-13 21:52 UTC, radekwojpl2 commented on src/index.js
>  const SW_API_BASE_URL = process.env.SW_API_BASE_URL || "https://swapi.dev/api";
same here, do we need that ?

2021-01-13 21:52 UTC, radekwojpl2 commented on src/app/MainMenu.js
> +  const API_KEY = 'a69c65ede3bb4ac3b262c5b425b4f835';
Every single feature should have its own API key, look at it on next PR

2021-01-13 21:52 UTC, radekwojpl2 commented on src/app/MainMenu.js
> +    sendRequest(inputForSearch)
I think you miss try/catch block here, send request will throw error on failure, then this error should be logged, we can think about it next time

2021-01-13 21:52 UTC, radekwojpl2 commented on src/app/MainMenu.js
> +  toggleBtn.addEventListener('click', e => {
I would avoid one-letter variables,  even when the variable is obvious

2021-01-13 23:33 UTC, mateugazi commented
I don't see any test files (I'm not sure if they should be committed, but I think it would be nice to see how you test it, because somebody could create the test that could find some error)

2021-01-14 22:46 UTC, mateugazi requested changes
I couldn't find invoking of the function 'MainMenu()' from 'MainMenu.js' in 'index.html', so I wondered if it's true and cloned this branch and test it locally and the 'index.html' was left blank. I had to create additional file which invoke this function here and after that the navbar appeared properly. Did I miss something or am I right?

2021-01-15 08:22 UTC, MaDud commented
> I couldn't find invoking of the function 'MainMenu()' from 'MainMenu.js' in 'index.html', so I wondered if it's true and cloned this branch and test it locally and the 'index.html' was left blank. I had to create additional file which invoke this function here and after that the navbar appeared properly. Did I miss something or am I right?

I remove it from index.html as I was using this file for test for 'MainMenu.js. I am not sure if it should be implemented on page which we don't use - if this will be place for our main page then of course it should be implemented by owner of this card. Now it is possible to see invoking of MainMenu function in recipe.js and at page './recipe.html'

2021-01-15 11:43 UTC, mateugazi approved these changes

2021-01-15 11:53 UTC, mateugazi commented
Oh now I see, then sorry for my inappropriate question. Everything looks good to me so you have my approval for this pr. Good job :)

2021-01-15 19:03 UTC, kingam280 approved these changes

2021-01-15 20:19 UTC, JotGabiga approved these changes
Great job!

2021-01-15 21:41 UTC, merged