Feature/nutrition game
radekwojpl2/CodersCamp2020.CookBook pull request #18
Opened 2021-01-15 09:55 UTC by kingam280

2021-01-15 20:28 UTC, mateugazi requested changes
Were you using parcel when you worked on that feature? I don't see that file in "package.json" -> "scripts" -> "start:dev" and in "build" (but that we can add at the end, when we finished the merging). When I add it to the parcel the game couldn't load, because of "Uncaught ReferenceError: regeneratorRuntime is not defined" . We are working on this project with parcel, so I think that should be fixed. I already fixed that in my local repo, but I also don't want to do something on your branch without your allowance, so I'm waiting for your answer

2021-01-15 21:12 UTC, kingam280 commented
I was working on live server from VS Code but it's fixed and should work now.

2021-01-15 21:18 UTC, mateugazi commented
Yes it works now, thanks.

2021-01-15 21:26 UTC, mateugazi commented on src/app/Game.js
> +    sumUpRound(question, timer, e) {
Radek said that we should avoid one letter variables, even when they are obvious

2021-01-15 21:27 UTC, mateugazi commented on src/app/Game.js
> +            this.checkBtn.addEventListener("click", (e) => e.preventDefault())
I will copy and paste previous comment: "Radek said that we should avoid one letter variables, even when they are obvious "

2021-01-15 21:31 UTC, mateugazi submitted a review, later dismissed
To me it's looks cool (I personally don't think that one name variable is a issue here) so you have my approval and btw great job :)

2021-01-17 09:05 UTC, MaDud submitted a review, later dismissed

2021-01-17 11:03 UTC, kingam280 commented on src/app/Question.js
> +            .then( res => res.json() )
Okay, I'll add if statement there

2021-01-17 14:42 UTC, mateugazi approved these changes

2021-01-17 14:44 UTC, mateugazi submitted a review, later dismissed

2021-01-17 18:21 UTC, MaDud approved these changes

2021-01-17 18:25 UTC, mateugazi approved these changes

2021-01-17 18:30 UTC, merged