Feature/calculator
radekwojpl2/CodersCamp2020.CookBook pull request #23
Opened 2021-01-17 18:29 UTC by mateugazi

2021-01-17 18:30 UTC, mateugazi commented on src/app/calculate.js
> +        const response = await fetch(`https://api.spoonacular.com/recipes/convert?ingredientName=this&sourceAmount=${sourceAmount}&sourceUnit=${sourceUnit}&targetUnit=${targetUnit}&apiKey=${apiKey}`)
I check if the fetch return error later

2021-01-17 19:44 UTC, kingam280 requested changes
You don't have all changes from main. For example menu doesn't look like it should

2021-01-17 19:44 UTC, kingam280 commented on src/app/calculator.js
> +MainMenu()
You should import MENU from GlobalData and add active page here

2021-01-17 19:44 UTC, kingam280 commented on calculator.html
> +    <script src="src/index.js" type="module"></script>
do you need it when you have your own file?

2021-01-17 19:44 UTC, kingam280 commented on test/calculator.test.js
> +test('xd', () => {
'xd'? :D

2021-01-17 19:44 UTC, kingam280 commented on calculator.html
> +    <link rel="stylesheet" href="styles/App.css" />
isn't it better to upload your css file? it may help avoid potential conflicts

2021-01-17 22:06 UTC, mateugazi commented
I changed everything you requested except file with 'xd'

2021-01-17 22:10 UTC, kingam280 approved these changes

2021-01-17 22:16 UTC, Yoruko90 approved these changes

2021-01-17 22:17 UTC, Yoruko90 approved these changes

2021-01-18 07:08 UTC, neacatsu approved these changes

2021-01-18 08:14 UTC, MaDud approved these changes
It looks fine for me. Good job

2021-01-18 08:14 UTC, MaDud commented on src/app/calculate.js
> +        const response = await fetch(`https://api.spoonacular.com/recipes/convert?ingredientName=this&sourceAmount=${sourceAmount}&sourceUnit=${sourceUnit}&targetUnit=${targetUnit}&apiKey=${apiKey}`)
Not complain just remaind :)

2021-01-18 09:33 UTC, radekwojpl2 approved these changes

2021-01-18 09:33 UTC, radekwojpl2 commented on test/calculator.test.js
> +test('xd', () => {
Better xd then something else XD

2021-01-18 10:07 UTC, JotGabiga approved these changes

2021-01-18 10:34 UTC, merged